import './globals.css'
import type { Metadata } from 'next'
import { Inter, Courgette } from 'next/font/google'
import Header from './components/Header'
import Footer from './components/Footer'

const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter'
})
const courgette = Courgette({ 
  weight: '400',
  subsets: ['latin'],
  variable: '--font-courgette'
});

export const metadata: Metadata = {
  title: 'CV Andréa Fourel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${courgette.variable} bg-light-sand relative`}>
        <Header />
        <main className='relative top-[25vh] left-[30vw] w-[45vw]'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
